version: '3.8'
services:
  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8888:8888"
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://db:27017/mendel
    # command:
    #   - /bin/sh -c "ts-node-dev --respawn -- src/app.ts"
    tty: true
    stdin_open: true